// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quer_user.proto

package cm.yuntongxun.grpc.service.user;

public final class QueryUser {
  private QueryUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface queryUserReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cm.yuntongxun.grpc.service.QueryUser.queryUserReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code cm.yuntongxun.grpc.service.QueryUser.queryUserReq}
   */
  public static final class queryUserReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cm.yuntongxun.grpc.service.QueryUser.queryUserReq)
      queryUserReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use queryUserReq.newBuilder() to construct.
    private queryUserReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private queryUserReq() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new queryUserReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private queryUserReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_queryUserReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_queryUserReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq.class, cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq)) {
        return super.equals(obj);
      }
      cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq other = (cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cm.yuntongxun.grpc.service.QueryUser.queryUserReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cm.yuntongxun.grpc.service.QueryUser.queryUserReq)
        cm.yuntongxun.grpc.service.user.QueryUser.queryUserReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_queryUserReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_queryUserReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq.class, cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq.Builder.class);
      }

      // Construct using cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_queryUserReq_descriptor;
      }

      @java.lang.Override
      public cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq getDefaultInstanceForType() {
        return cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq.getDefaultInstance();
      }

      @java.lang.Override
      public cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq build() {
        cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq buildPartial() {
        cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq result = new cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq) {
          return mergeFrom((cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq other) {
        if (other == cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cm.yuntongxun.grpc.service.QueryUser.queryUserReq)
    }

    // @@protoc_insertion_point(class_scope:cm.yuntongxun.grpc.service.QueryUser.queryUserReq)
    private static final cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq();
    }

    public static cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<queryUserReq>
        PARSER = new com.google.protobuf.AbstractParser<queryUserReq>() {
      @java.lang.Override
      public queryUserReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new queryUserReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<queryUserReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<queryUserReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cm.yuntongxun.grpc.service.user.QueryUser.queryUserReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryUserReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cm.yuntongxun.grpc.service.QueryUser.QueryUserReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
     */
    java.util.List<cm.yuntongxun.grpc.service.user.QueryUser.UserInfo> 
        getUserInfoList();
    /**
     * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
     */
    cm.yuntongxun.grpc.service.user.QueryUser.UserInfo getUserInfo(int index);
    /**
     * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
     */
    int getUserInfoCount();
    /**
     * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
     */
    java.util.List<? extends cm.yuntongxun.grpc.service.user.QueryUser.UserInfoOrBuilder> 
        getUserInfoOrBuilderList();
    /**
     * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
     */
    cm.yuntongxun.grpc.service.user.QueryUser.UserInfoOrBuilder getUserInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cm.yuntongxun.grpc.service.QueryUser.QueryUserReply}
   */
  public static final class QueryUserReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cm.yuntongxun.grpc.service.QueryUser.QueryUserReply)
      QueryUserReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryUserReply.newBuilder() to construct.
    private QueryUserReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryUserReply() {
      userInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryUserReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryUserReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                userInfo_ = new java.util.ArrayList<cm.yuntongxun.grpc.service.user.QueryUser.UserInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              userInfo_.add(
                  input.readMessage(cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          userInfo_ = java.util.Collections.unmodifiableList(userInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_QueryUserReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_QueryUserReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply.class, cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply.Builder.class);
    }

    public static final int USERINFO_FIELD_NUMBER = 1;
    private java.util.List<cm.yuntongxun.grpc.service.user.QueryUser.UserInfo> userInfo_;
    /**
     * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
     */
    @java.lang.Override
    public java.util.List<cm.yuntongxun.grpc.service.user.QueryUser.UserInfo> getUserInfoList() {
      return userInfo_;
    }
    /**
     * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends cm.yuntongxun.grpc.service.user.QueryUser.UserInfoOrBuilder> 
        getUserInfoOrBuilderList() {
      return userInfo_;
    }
    /**
     * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
     */
    @java.lang.Override
    public int getUserInfoCount() {
      return userInfo_.size();
    }
    /**
     * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
     */
    @java.lang.Override
    public cm.yuntongxun.grpc.service.user.QueryUser.UserInfo getUserInfo(int index) {
      return userInfo_.get(index);
    }
    /**
     * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
     */
    @java.lang.Override
    public cm.yuntongxun.grpc.service.user.QueryUser.UserInfoOrBuilder getUserInfoOrBuilder(
        int index) {
      return userInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < userInfo_.size(); i++) {
        output.writeMessage(1, userInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < userInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply)) {
        return super.equals(obj);
      }
      cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply other = (cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply) obj;

      if (!getUserInfoList()
          .equals(other.getUserInfoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUserInfoCount() > 0) {
        hash = (37 * hash) + USERINFO_FIELD_NUMBER;
        hash = (53 * hash) + getUserInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cm.yuntongxun.grpc.service.QueryUser.QueryUserReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cm.yuntongxun.grpc.service.QueryUser.QueryUserReply)
        cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_QueryUserReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_QueryUserReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply.class, cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply.Builder.class);
      }

      // Construct using cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userInfoBuilder_ == null) {
          userInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userInfoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_QueryUserReply_descriptor;
      }

      @java.lang.Override
      public cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply getDefaultInstanceForType() {
        return cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply.getDefaultInstance();
      }

      @java.lang.Override
      public cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply build() {
        cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply buildPartial() {
        cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply result = new cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply(this);
        int from_bitField0_ = bitField0_;
        if (userInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            userInfo_ = java.util.Collections.unmodifiableList(userInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply) {
          return mergeFrom((cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply other) {
        if (other == cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply.getDefaultInstance()) return this;
        if (userInfoBuilder_ == null) {
          if (!other.userInfo_.isEmpty()) {
            if (userInfo_.isEmpty()) {
              userInfo_ = other.userInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserInfoIsMutable();
              userInfo_.addAll(other.userInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.userInfo_.isEmpty()) {
            if (userInfoBuilder_.isEmpty()) {
              userInfoBuilder_.dispose();
              userInfoBuilder_ = null;
              userInfo_ = other.userInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserInfoFieldBuilder() : null;
            } else {
              userInfoBuilder_.addAllMessages(other.userInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cm.yuntongxun.grpc.service.user.QueryUser.UserInfo> userInfo_ =
        java.util.Collections.emptyList();
      private void ensureUserInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          userInfo_ = new java.util.ArrayList<cm.yuntongxun.grpc.service.user.QueryUser.UserInfo>(userInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cm.yuntongxun.grpc.service.user.QueryUser.UserInfo, cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder, cm.yuntongxun.grpc.service.user.QueryUser.UserInfoOrBuilder> userInfoBuilder_;

      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public java.util.List<cm.yuntongxun.grpc.service.user.QueryUser.UserInfo> getUserInfoList() {
        if (userInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userInfo_);
        } else {
          return userInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public int getUserInfoCount() {
        if (userInfoBuilder_ == null) {
          return userInfo_.size();
        } else {
          return userInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public cm.yuntongxun.grpc.service.user.QueryUser.UserInfo getUserInfo(int index) {
        if (userInfoBuilder_ == null) {
          return userInfo_.get(index);
        } else {
          return userInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public Builder setUserInfo(
          int index, cm.yuntongxun.grpc.service.user.QueryUser.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfoIsMutable();
          userInfo_.set(index, value);
          onChanged();
        } else {
          userInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public Builder setUserInfo(
          int index, cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          userInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public Builder addUserInfo(cm.yuntongxun.grpc.service.user.QueryUser.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfoIsMutable();
          userInfo_.add(value);
          onChanged();
        } else {
          userInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public Builder addUserInfo(
          int index, cm.yuntongxun.grpc.service.user.QueryUser.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfoIsMutable();
          userInfo_.add(index, value);
          onChanged();
        } else {
          userInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public Builder addUserInfo(
          cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.add(builderForValue.build());
          onChanged();
        } else {
          userInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public Builder addUserInfo(
          int index, cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          userInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public Builder addAllUserInfo(
          java.lang.Iterable<? extends cm.yuntongxun.grpc.service.user.QueryUser.UserInfo> values) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userInfo_);
          onChanged();
        } else {
          userInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public Builder removeUserInfo(int index) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.remove(index);
          onChanged();
        } else {
          userInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder getUserInfoBuilder(
          int index) {
        return getUserInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public cm.yuntongxun.grpc.service.user.QueryUser.UserInfoOrBuilder getUserInfoOrBuilder(
          int index) {
        if (userInfoBuilder_ == null) {
          return userInfo_.get(index);  } else {
          return userInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public java.util.List<? extends cm.yuntongxun.grpc.service.user.QueryUser.UserInfoOrBuilder> 
           getUserInfoOrBuilderList() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userInfo_);
        }
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder addUserInfoBuilder() {
        return getUserInfoFieldBuilder().addBuilder(
            cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder addUserInfoBuilder(
          int index) {
        return getUserInfoFieldBuilder().addBuilder(
            index, cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .cm.yuntongxun.grpc.service.QueryUser.UserInfo userInfo = 1;</code>
       */
      public java.util.List<cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder> 
           getUserInfoBuilderList() {
        return getUserInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cm.yuntongxun.grpc.service.user.QueryUser.UserInfo, cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder, cm.yuntongxun.grpc.service.user.QueryUser.UserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cm.yuntongxun.grpc.service.user.QueryUser.UserInfo, cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder, cm.yuntongxun.grpc.service.user.QueryUser.UserInfoOrBuilder>(
                  userInfo_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cm.yuntongxun.grpc.service.QueryUser.QueryUserReply)
    }

    // @@protoc_insertion_point(class_scope:cm.yuntongxun.grpc.service.QueryUser.QueryUserReply)
    private static final cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply();
    }

    public static cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryUserReply>
        PARSER = new com.google.protobuf.AbstractParser<QueryUserReply>() {
      @java.lang.Override
      public QueryUserReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryUserReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryUserReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryUserReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cm.yuntongxun.grpc.service.user.QueryUser.QueryUserReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cm.yuntongxun.grpc.service.QueryUser.UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>sint64 ip = 3;</code>
     * @return The ip.
     */
    long getIp();
  }
  /**
   * Protobuf type {@code cm.yuntongxun.grpc.service.QueryUser.UserInfo}
   */
  public static final class UserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cm.yuntongxun.grpc.service.QueryUser.UserInfo)
      UserInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfo() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 24: {

              ip_ = input.readSInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_UserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.class, cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int IP_FIELD_NUMBER = 3;
    private long ip_;
    /**
     * <code>sint64 ip = 3;</code>
     * @return The ip.
     */
    @java.lang.Override
    public long getIp() {
      return ip_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (ip_ != 0L) {
        output.writeSInt64(3, ip_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (ip_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(3, ip_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cm.yuntongxun.grpc.service.user.QueryUser.UserInfo)) {
        return super.equals(obj);
      }
      cm.yuntongxun.grpc.service.user.QueryUser.UserInfo other = (cm.yuntongxun.grpc.service.user.QueryUser.UserInfo) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (getIp()
          != other.getIp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cm.yuntongxun.grpc.service.user.QueryUser.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cm.yuntongxun.grpc.service.QueryUser.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cm.yuntongxun.grpc.service.QueryUser.UserInfo)
        cm.yuntongxun.grpc.service.user.QueryUser.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_UserInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.class, cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.Builder.class);
      }

      // Construct using cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = "";

        age_ = 0;

        ip_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cm.yuntongxun.grpc.service.user.QueryUser.internal_static_cm_yuntongxun_grpc_service_QueryUser_UserInfo_descriptor;
      }

      @java.lang.Override
      public cm.yuntongxun.grpc.service.user.QueryUser.UserInfo getDefaultInstanceForType() {
        return cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.getDefaultInstance();
      }

      @java.lang.Override
      public cm.yuntongxun.grpc.service.user.QueryUser.UserInfo build() {
        cm.yuntongxun.grpc.service.user.QueryUser.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cm.yuntongxun.grpc.service.user.QueryUser.UserInfo buildPartial() {
        cm.yuntongxun.grpc.service.user.QueryUser.UserInfo result = new cm.yuntongxun.grpc.service.user.QueryUser.UserInfo(this);
        result.message_ = message_;
        result.age_ = age_;
        result.ip_ = ip_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cm.yuntongxun.grpc.service.user.QueryUser.UserInfo) {
          return mergeFrom((cm.yuntongxun.grpc.service.user.QueryUser.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cm.yuntongxun.grpc.service.user.QueryUser.UserInfo other) {
        if (other == cm.yuntongxun.grpc.service.user.QueryUser.UserInfo.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getIp() != 0L) {
          setIp(other.getIp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cm.yuntongxun.grpc.service.user.QueryUser.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cm.yuntongxun.grpc.service.user.QueryUser.UserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private long ip_ ;
      /**
       * <code>sint64 ip = 3;</code>
       * @return The ip.
       */
      @java.lang.Override
      public long getIp() {
        return ip_;
      }
      /**
       * <code>sint64 ip = 3;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(long value) {
        
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cm.yuntongxun.grpc.service.QueryUser.UserInfo)
    }

    // @@protoc_insertion_point(class_scope:cm.yuntongxun.grpc.service.QueryUser.UserInfo)
    private static final cm.yuntongxun.grpc.service.user.QueryUser.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cm.yuntongxun.grpc.service.user.QueryUser.UserInfo();
    }

    public static cm.yuntongxun.grpc.service.user.QueryUser.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
      @java.lang.Override
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cm.yuntongxun.grpc.service.user.QueryUser.UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cm_yuntongxun_grpc_service_QueryUser_queryUserReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cm_yuntongxun_grpc_service_QueryUser_queryUserReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cm_yuntongxun_grpc_service_QueryUser_QueryUserReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cm_yuntongxun_grpc_service_QueryUser_QueryUserReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cm_yuntongxun_grpc_service_QueryUser_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cm_yuntongxun_grpc_service_QueryUser_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017quer_user.proto\022$cm.yuntongxun.grpc.se" +
      "rvice.QueryUser\"\034\n\014queryUserReq\022\014\n\004name\030" +
      "\001 \001(\t\"R\n\016QueryUserReply\022@\n\010userInfo\030\001 \003(" +
      "\0132..cm.yuntongxun.grpc.service.QueryUser" +
      ".UserInfo\"4\n\010UserInfo\022\017\n\007message\030\001 \001(\t\022\013" +
      "\n\003age\030\002 \001(\005\022\n\n\002ip\030\003 \001(\0222\206\001\n\013UserService\022" +
      "w\n\tqueryUser\0222.cm.yuntongxun.grpc.servic" +
      "e.QueryUser.queryUserReq\0324.cm.yuntongxun" +
      ".grpc.service.QueryUser.QueryUserReply\"\000" +
      "B.\n\037cm.yuntongxun.grpc.service.userB\tQue" +
      "ryUserP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cm_yuntongxun_grpc_service_QueryUser_queryUserReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cm_yuntongxun_grpc_service_QueryUser_queryUserReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cm_yuntongxun_grpc_service_QueryUser_queryUserReq_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_cm_yuntongxun_grpc_service_QueryUser_QueryUserReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cm_yuntongxun_grpc_service_QueryUser_QueryUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cm_yuntongxun_grpc_service_QueryUser_QueryUserReply_descriptor,
        new java.lang.String[] { "UserInfo", });
    internal_static_cm_yuntongxun_grpc_service_QueryUser_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cm_yuntongxun_grpc_service_QueryUser_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cm_yuntongxun_grpc_service_QueryUser_UserInfo_descriptor,
        new java.lang.String[] { "Message", "Age", "Ip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
